#services:
#  db:
#    image: postgres:16-alpine
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: restore_express
#    ports:
#      - "5433:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8081:8080"
#
#volumes:
#  postgres_data:

services:
  app:
    build: .
    restart: always
    ports:
      - "80:8080"
    environment:
      # Use internal Docker network name 'db' and default port 5432
      DB_URL: "jdbc:postgresql://db:5432/restore_express"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password_here
      POSTGRES_DB: restore_express
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  postgres_data:
