services:
  app:
    image: eclipse-temurin:21-jre-alpine
    restart: always
    working_dir: /app
    volumes:
      - ./app.jar:/app/app.jar:ro
    command: ["java", "-Xmx384m", "-Xms128m", "-jar", "app.jar"]
    ports:
      - "80:8080"
    environment:
      DATABASE_URL: "jdbc:postgresql://db:5432/restore_express"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restore_express
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  postgres_data:
